name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: rejo/focus-log
          stage: main
          yaml: |
            name: focus-log-be
            app: python@3.10
            options:
              env:
                - name: DB_HOST
                  value: focus-log-db
                - name: DB_PORT
                  secret: DB_PORT
                - name: DB_USER
                  secret: DB_USER
                - name: DB_PASSWORD
                  secret: DB_PASSWORD
                - name: DB_NAME
                  secret: DB_NAME
              ports: 8000
              start: uvicorn main:app --host=0.0.0.0 --port=8000
              install: pip install -r requirements.txt
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: python-fastapi